sudo: required
services:
  - docker

before_install:
  - docker build -t satzy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true satzy/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-handson"
  env: "Docker-handson-env"
  bucket_name: "elasticbeanstalk-us-east-1-003773012327"
  bucket_path: "docker-handson"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"